### PR TITLE
Release to both github and pypi via workflow

### PR DESCRIPTION
**Pull request by ahmubashshir**
## Changes:
- workflow: Add release workflow
- poetry.lock: Corrupt urlmatch OS X tarball checksum to avoid it

## Requirements:
Pypi.org auth token added as a secret named `PYPI_TOKEN`

### CODE REVIEW

**Comment by iamkroot** [comment]
Blocked by pypa/pypi-support#1735

**Comment by iamkroot** [comment]
With poetry 1.2, we don't need to corrupt the urlmatch checksum anymore

**Comment by iamkroot** [comment]
Hey @ahmubashshir I have updated the workflow a bit. But github isn't allowing me to push to that from the CLI for some reason (permission denied). Could you please try adding me as a collaborator to your fork so I can try again?

**Comment by iamkroot** [comment]
@ahmubashshir Seems like there are conflicts. Can be fixed with `git rebase master --strategy-option=theirs`.

I can't do a force-push on your branch, so you'll need to run that. Then we should be able to merge this

**Comment by ahmubashshir** [comment]
On October 23, 2022 7:18:32 AM UTC, Krut Patel ***@***.***> wrote:
***@***.*** Seems like there are conflicts. Can be fixed with `git rebase master --strategy-option=theirs`.
>
>I can't do a force-push on your branch, so you'll need to run that. Then we should be able to merge this
>

My box is borked. That'll take a few more days...

**Comment by ahmubashshir** [comment]
does it work now?

**Comment by iamkroot** [comment]
Looks good!

**Pull request merged**
